version: "3"
services:
  chrome:
    image: seleniarm/standalone-chromium:latest #ARM => M1 Chip
    # image: selenium/node-chrome:4.7.0-20221202
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    expose:
      - 4444
    networks:
      - selenium
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 15s
      timeout: 30s
      retries: 5

  python:
    build: .
    platform: linux/amd64 #ARM => M1 Chip
    networks:
      - selenium
    env_file:
      - ./.env
    depends_on:
      chrome:
        condition: service_healthy

networks:
  selenium:
    driver: bridge

